-- create table for hirc pm report data
DROP TABLE IF EXISTS hirc_pm_report;

CREATE TABLE hirc_pm_report (
    object_id TEXT,
    INTAKE_SUBMIT_DATE TEXT,	
    PHASE TEXT,
    FUND_CATG TEXT,
    FUND_DESC TEXT,	
    SHORT_TITLE	TEXT,
    STUDY_TITLE	TEXT,
    PI_NAME	TEXT,
    PI_TYPE	TEXT,
    PM_NAME_1 TEXT,	
    PROJ_TYPE TEXT,
    CRC_NAME_1	TEXT,
    ENROLL_TARGET TEXT,
    PROGRESS_NOTE TEXT,
    IRB_NUM	TEXT,
    IRB_APV_DATE TEXT,
    IRB_CLOSURE_DATE TEXT,
    RSCH_THEME	TEXT,
    RSCH_CATG	TEXT,
    RSCH_TYPE TEXT
);

-- add data from temp table
INSERT INTO hirc_pm_report (
    object_id, INTAKE_SUBMIT_DATE,PHASE , FUND_CATG ,FUND_DESC ,SHORT_TITLE	,STUDY_TITLE ,PI_NAME,PI_TYPE,PM_NAME_1 ,PROJ_TYPE,CRC_NAME_1 ,ENROLL_TARGET ,PROGRESS_NOTE ,IRB_NUM,IRB_APV_DATE,IRB_CLOSURE_DATE ,RSCH_THEME,RSCH_CATG,RSCH_TYPE
) 
SELECT
    object_id, INTAKE_SUBMIT_DATE,PHASE , FUND_CATG ,FUND_DESC ,SHORT_TITLE	,STUDY_TITLE ,PI_NAME,PI_TYPE,PM_NAME_1 ,PROJ_TYPE,CRC_NAME_1 ,ENROLL_TARGET ,PROGRESS_NOTE ,IRB_NUM,IRB_APV_DATE,IRB_CLOSURE_DATE ,RSCH_THEME,RSCH_CATG,RSCH_TYPE
FROM temp_report
;

-- filter specific columns
DROP TABLE IF EXISTS hirc_pm_report_cleaned;

CREATE TABLE hirc_pm_report_cleaned AS 
SELECT
    object_id,
    INTAKE_SUBMIT_DATE,	
    PHASE,
    FUND_CATG,
    SHORT_TITLE,
    PI_NAME,
    PI_TYPE,
    PM_NAME_1,	
    PROJ_TYPE,
    RSCH_THEME,
    RSCH_CATG,
    RSCH_TYPE
FROM hirc_pm_report
;

